Added sort by default to nodes
hikerpig/gatsby-project-kb pull request #58
Opened 2022-10-15 12:50 UTC by jessems

By default the nodes are sorted by id, not by title or relativePath. This is a bit counter intuitive when you have a bunch of markdown files and folders with alphabetic sorting (e.g. "01 this is the first file" and "02 this is the second file") and they don't appear in the same sequence in the sidebar menu.

This little sort fixes that.
<img width="264" alt="image" src="https://user-images.githubusercontent.com/3264264/195987333-803bbe9a-08e6-4338-8c05-656f54c3d3aa.png">

2022-10-17 02:40 UTC, hikerpig requested changes
Thank you for this nice enhancement.
I've leave one comment regard of the code.

2022-10-17 02:40 UTC, hikerpig commented on packages/gatsby-theme-kb/src/components/SiteSidebar/index.tsx
> +    nodes = nodes.sort((a,b) => {
Maybe we should sort `validNodes` instead ?
Because in line 85 we see there might be a chance that `node.parent` does not exist, in this situation line 81 may throw an error.

2022-10-17 05:55 UTC, hikerpig commented
It occurred to me that sorting by relativePath will also cause some confusions because sidebars displays title rather than file path. So it sometimes will look strange if file path and title are not the same.
I think it'd be better if the sorting can be configured, but this PR itself is good enough to be merged (with the problem in my CR comment fixed of course. It's a good default behavior this way. And I will make it configurable later.
<img width="305" alt="image" src="https://user-images.githubusercontent.com/2259688/196098862-cab6b606-0f29-4210-9dba-7d49e49df2a2.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/2259688/196098947-e77fe6bf-d852-44e2-a730-b47e55a5d997.png">

2022-10-17 16:54 UTC, jessems commented on packages/gatsby-theme-kb/src/components/SiteSidebar/index.tsx
> +    nodes = nodes.sort((a,b) => {
Yes! That makes more sense. I'll revise.

2022-10-17 17:12 UTC, jessems commented
Updated the pull request to sort on validNodes. And I agree with you, having the option to sort on title would be even better. I ran into a case where I needed it already.

2022-10-18 01:01 UTC, merged

2025-01-24 02:23 UTC, subhodeeps commented
Hi, will this be incorporated in the theme anytime soon? In the meantime, how can I implement this locally if I'm using the template? 

Thanks for the template btw. It's really cool and must have taken a lot of work!